version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: attendance_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - attendance_net

  auth_service:
    build: ./auth_service
    container_name: auth_microservice
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    volumes:
      - ./img_students:/app/img_students  
    environment:
      - MONGO_URI=mongodb://mongodb:27017/attendance_system
      - JWT_SECRET=super_secret_its_2026
      - TZ=Europe/Rome
    networks:
      - attendance_net

  detection_service:
    build: ./detection_service
    container_name: detection_microservice
    ports:
      - "5002:5000"
    depends_on:
      - mongodb
    volumes:
      - ./img_students:/app/img_students
    networks:
      - attendance_net
    environment:
      - MONGO_URI=mongodb://mongodb:27017/attendance_system
      - JWT_SECRET=super_secret_its_2026
      - TZ=Europe/Rome

networks:
  attendance_net:
    driver: bridge

volumes:
  mongo_data: